--[=[
Sheepdog World of Warcraft Add-on
Copyright (c) 2011-2018 by John Wellesz (Sheepdog@2072productions.com)
All rights reserved

Version @project-version@

A very simple add-on that should prevent you from breaking crowd control spell.

This add-on uses the Ace3 framework.

type /Sheepdog to get a list of existing options.

-----
    Localization.lua
-----


--]=]


--[=[
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating Sheepdog.
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ########################################################
--      #  http://www.wowace.com/addons/sheepdog/localization/ #                  #
--      ########################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--]=]


do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "enUS", true, true);

    if L then
        --@localization(locale="enUS", format="lua_additive_table")@

    --@do-not-package@
    ---[==[
    -- Used for testing the addon without the packager
    L["VERSION"] = "version:"
    L["RELEASE_DATE"] = "Release Date:"
    L["ENABLED"] = "enabled! Type /Sheepdog for options"
    L["DISABLED"] = "Sheepdog has been disabled!"
    L["DESCRIPTION"] = "A very simple add-on that should prevent you from accidentally breaking crowd-control spells."

    L["OPT_ON"] = "on"
    L["OPT_ON_DESC"] = "Enables Sheepdog"

    L["OPT_OFF"] = "off"
    L["OPT_OFF_DESC"] = "Disables Sheepdog"

    L["OPT_VERSION"] = "version"
    L["OPT_VERSION_DESC"] = "Display version and release date"

    L["OPT_DEBUG"] = "Debug"
    L["OPT_DEBUG_DESC"] = "Enables / disables debugging"

    L["OPT_TARGETING_SOUND"] = "Targeting Sound"
    L["OPT_TARGETING_SOUND_DESC"] = "Choose the sound Sheepdog will play when you target a crowd controlled unit"

    L["OPT_ALERT_SOUND"] = "Alert Sound"
    L["OPT_ALERT_SOUND_DESC"] = "Choose the sound Sheepdog will play when a unit is crowd-controlled nearby"

    L["OPT_NEARBYALERT"] = "Nearby crowd-control alerts"
    L["OPT_NEARBYALERT_DESC"] = "Alerts you when something is being crowd-controlled somewhere around you"

    L["OPT_USERAIDALERTFRAME"] = "Use raid alerts' frame"
    L["OPT_USERAIDALERTFRAME_DESC"] = "Display messages using the raid alert style (only uses the style, no actual raid alert is made)"

    L["OPT_WELCOMEMESSAGE"] = "Welcome message"
    L["OPT_WELCOMEMESSAGE_DESC"] = "Display a message when Sheepdog is loaded"

    L["TARGET_IS_CROWD_CONTROLLED"] = "Your target is crowd-controlled!"

    L["UNIT_NEARBY_IS_CROWD_CONTROLLED"] = "%q applied on %s by %s!"

    L["PRINT_SUPPOTED_CC"] = "Show supported spells"
    L["PRINT_SUPPOTED_CC_DESC"] = "Print supported spells in the chat"

    --]==]
    --@end-do-not-package@

    end

end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "frFR");

    if L then
        --@localization(locale="frFR", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "deDE");

    if L then
        --@localization(locale="deDE", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "esES");

    if L then
        --@localization(locale="esES", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "esMX");

    if L then
        --@localization(locale="esMX", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "koKR");

    if L then
        --@localization(locale="koKR", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "zhCN");

    if L then
        --@localization(locale="zhCN", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "zhTW");

    if L then
        --@localization(locale="zhTW", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("Sheepdog", "ruRU");

    if L then
        --@localization(locale="ruRU", format="lua_additive_table")@
    end
end


