--[=[
SheepDog World of Warcraft Add-on
Copyright (c) 2011 by John Wellesz (Archarodim@teaser.fr)
All rights reserved

Version @project-version@

A very simple add-on that should prevent you from breaking crowd control spell.

This add-on uses the Ace3 framework.

type /SheepDog to get a list of existing options.

-----
    Localization.lua
-----


--]=]


--[=[
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating SheepDog.
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ########################################################
--      #  http://www.wowace.com/addons/sheepdog/localization/ #                  #
--      ########################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--]=]


do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "enUS", true, true);

    if L then
        --@localization(locale="enUS", format="lua_additive_table")@

    --@do-not-package@
    ---[==[
    -- Used for testing the addon without the packager
    L["VERSION"] = "version:"
    L["RELEASE_DATE"] = "Release Date:"
    L["ENABLED"] = "enabled! Type /SheepDog for a list of options"
    L["DISABLED"] = "SheepDog has been disabled!\nType /SheepDog on."

    L["OPT_ON"] = "on"
    L["OPT_ON_DESC"] = "Enables SheepDog"

    L["OPT_OFF"] = "off"
    L["OPT_OFF_DESC"] = "Disables SheepDog"

    L["OPT_VERSION"] = "version"
    L["OPT_VERSION_DESC"] = "Display version and release date"

    L["OPT_DEBUG"] = "debug"
    L["OPT_DEBUG_DESC"] = "Enables / disables debugging"

    L["OPT_TARGETING_SOUND"] = "Targetting Sound"
    L["OPT_TARGETING_SOUND_DESC"] = "Choose the sound SheepDog will play when you target a crowd controlled unit"

    L["TARGET_IS_CROWD_CONTROLLED"] = "Your target is crowd controlled!"

    --]==]
    --@end-do-not-package@

    end

end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "frFR");

    if L then
        --@localization(locale="frFR", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "deDE");

    if L then
        --@localization(locale="deDE", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "esES");

    if L then
        --@localization(locale="esES", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "esMX");

    if L then
        --@localization(locale="esMX", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "koKR");

    if L then
        --@localization(locale="koKR", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "zhCN");

    if L then
        --@localization(locale="zhCN", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "zhTW");

    if L then
        --@localization(locale="zhTW", format="lua_additive_table")@
    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("SheepDog", "ruRU");

    if L then
        --@localization(locale="ruRU", format="lua_additive_table")@
    end
end


